os: osx
language: objective-c
osx_image: xcode9.1
# os: linux
# language: generic
# dist: trusty
script:
  - swift --version
  - swift build
  - swift test
before_install:
  - chmod ugo+x ./Scripts/travis.bash
  - source ./Scripts/travis.bash

